spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/kada
    driverClassName: org.postgresql.Driver
    username: postgres
    password: postgres
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 30000
      pool-name: CargoHikariCP

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        jdbc:
          batch_size: 50
        envers:
          default_schema: aud
          store_data_at_delete: true
    open-in-view: false

  logging:
    level:
      org.hibernate.SQL: DEBUG
      org.hibernate.type.descriptor.sql: TRACE

  freemarker:
    template-loader-path: classpath:/templates/
    suffix: .ftl
    charset: UTF-8
    check-template-location: true
    settings:
      number_format: computer

  mvc:
    throw-exception-if-no-handler-found: true

  web:
    resources:
      add-mappings: false

server:
  error:
    whitelabel:
      enabled: false
